### ISSUE TITLE
[BUG] Siri Commands Still Open Apple Maps

### ISSUE THREAD

**Issue by Hydroxing** [LorenzoPane/EvilScheme#43] opened 2021-01-25 18:32 UTC
**Describe the bug**
When telling Siri for directions to x place, the command is sent to Apple Maps and does not use Google Maps as the default

**To Reproduce**
1. Set Default App for Google Maps
2. Invoke Siri 
3. Ask Siri for directions to a place near you that you know of, e.g. “home” or “gas station”
4. Directions are sent to Apple Maps and not using Google Maps

**Expected behavior**
With Google Maps selected as Default Map Preset, all Apple Map links should redirect to handle opening in Google Maps

**Screenshots**
None applicable at this time.

**Extra Info**
Please include
1. iPhone Xs Max
2. 13.5
3. 0.2.4
4. No crash report
5. unc0ver jailbreak 5.3.1
6. Package manager: Zebra

**Comment by LorenzoPane** [comment] 2021-01-26 13:09
Duplicate of #16

**Closed as completed by LorenzoPane** 2021-01-26 13:09 UTC
Labels: bug
