### ISSUE TITLE
[BUG] Gmail preset not working

### ISSUE THREAD

**Issue by XCoolBeatX** [LorenzoPane/EvilScheme#13] opened 2020-06-03 04:12 UTC
**Describe the bug**
When clicking on a mailto link which should open the gmail app with the email in it, is not working. Ita still opening the Apple Mail

**Extra Info**
Please include
1. iPhone XR
2. iOS 13.5
3. Evil Scheme version: 0.1.1

**Comment by LorenzoPane** [comment] 2020-06-07 21:48
I'm assuming this is a duplicate of #4. If not, I'm unable to recreate it, so I'm closing anyway. Let me know if there is something I'm missing.

**Closed as completed by LorenzoPane** 2020-06-07 21:48 UTC
Labels: bug
