### ISSUE TITLE
[FEATURE REQUEST] Change default browser also for home shortcuts

### ISSUE THREAD

**Issue by antoniomcr96** [LorenzoPane/EvilScheme#29] opened 2020-06-11 19:19 UTC
If I add a shortcut to home with Safari, it will open with Safari. Is it possible to change this behavior with evil scheme ? Is there any prefix I can use?
Thanks in advance

**Comment by LorenzoPane** [comment] 2020-06-11 19:26
Duplicate of #25

**Closed as completed by LorenzoPane** 2020-06-11 19:26 UTC
Labels: enhancement

**Comment by antoniomcr96** [comment] 2020-06-11 19:29
> Duplicate of #25

Sorry, I didn’t see. Thank you for the awesome work. Ciao!
